### DISCUSSION TITLE
부하 테스트 과정에서 어떤 지표들을 모니터링 해야 할까?

### DISCUSSION THREAD

**Discussion by devjun10** [dailyge/dailyge-server#82] [Performance]
## 📝 연관 PR

- [[DLG-144] 부하 테스트를 위해 User Email 길이를 최대까지 허용한다.](https://github.com/dailyge/dailyge-server/pull/79#issuecomment-2294463801)
- [[DLG-161] GC, HeapDump 설정을 추가한다.](https://github.com/dailyge/dailyge-server/pull/95)

<br/><br/>

## ❓ 작성 이유

성능 테스트를 할 때, 우리 애플리케이션의 **`어떤 대상`** 을, **`어떤 지표`** 를 모니터링할 지 정해야 합니다. 다양한 지표들이 있지만 간단하게 프로젝트에서 모니터링 중인 애플리케이션, 데이터베이스 두 가지에 대해 살펴보겠습니다.

1. 애플리케이션
2. 데이터베이스

<br/><br/>

## 1. 애플리케이션

애플리케이션에서는 크게 **`CPU/Memory 사용률`**, **`응답 속도`**, **`쓰레드 상태`** 를 체크해야 합니다.

1. CPU/Memory 사용률
2. 응답 속도
3. 쓰레드 상태

<br/><br/>

### 1-1. CPU/Memory 사용률

부하를 주면 CPU 사용률이 급격하게 증가할 수 있습니다. 이는 **`컨텍스트 스위칭`** 이 빈번하게 발생하기 때문인데, 한정된 CPU 자원 내에서 많은 쓰레드가 실행되면, 특정 쓰레드가 Blocking 당할 때마다 다른 쓰레드의 문맥(Context)을 스위칭하여 하기 때문입니다. 

![image](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FdmLQuB%2FbtsJqibt0xv%2Fi2l1xJxEEo8Sykjgk8M5m1%2Fimg.png)

> 이는 프로세스의 CPU 사용률과 서버의 CPU 사용률 모두를 체크해야 합니다.

<br/><br/><br/><br/>

이 과정에서 CPU 사용률이 증가하게 되며, 이는 톰캣의 쓰레드 개수와도 연관이 있습니다. 무작정 많은 쓰레드를 할당하면 CPU가 여러 쓰레드 간에 컨텍스트 스위칭을 더 자주 해야 하기 때문에 CPU 부하가 심해질 수 있습니다. 반대로, 너무 적은 쓰레드를 할당하면 요청이 큐에 쌓이면서 응답 지연이 발생해 타임아웃이 발생합니다. 따라서 시스템의 CPU 코어 수와 실제 처리량에 맞는 적절한 쓰레드 수를 설정하는 것이 중요합니다.

```yml
server:
  tomcat:
    accept-count: ${ACCEPT_COUNT}
    max-connections: ${MAX_CONNECTIONS}
    connection-timeout: 15000
    uri-encoding: UTF-8
    background-processor-delay: 10
    threads:
      max: ${MAX}
      min-spare: ${MIN_SPARE}
```

<br/><br/><br/><br/>

### 1-2. 응답 속도

스프링 MVC를 사용하면 톰캣의 쓰레드 개수는 한정되어 있습니다. 응답 속도가 느리면 accept-queue에 들어가 대기하는 요청이 많아지며, 이들이 많아지면 타임아웃이 발생하거나 요청이 거부됩니다. 따라서 요청을 빠르게 처리할 수 있어야 합니다.

![image](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fcsnjvz%2FbtsJiHwtriH%2FeYKls96pwj6jkFFYtagoh0%2Fimg.png)

<br/><br/><br/><br/>

### 1-3. 쓰레드 상태

서버 스펙을 고려해 적절한 쓰레드를 할당해야 합니다. 

<br/><br/><br/><br/>

## 2. 데이터베이스

데이터베이스는 RDB, Redis 두 가지만 살펴보겠습니다. 

1. RDB: 커넥션, 
4. Redis: Memory Usage, Blocking, 네트워크 I/O,

<br/><br/><br/><br/>
