### DISCUSSION TITLE
부하 테스트를 할 때, 톰캣의 어떤 설정들을 고려해야 할까?

### DISCUSSION THREAD

**Discussion by devjun10** [dailyge/dailyge-server#84] [Information]
## 🔗 연관 PR

- [[DLG-144] 부하 테스트를 위해 User Email 길이를 최대까지 허용한다.](https://github.com/dailyge/dailyge-server/pull/79#issuecomment-2294463801)
- [[DLG-161] GC, HeapDump 설정을 추가한다.](https://github.com/dailyge/dailyge-server/pull/95)
- [[DLG-165] 캐시 저장 로직을 리팩토링한다.](https://github.com/dailyge/dailyge-server/pull/98)

<br/><br/>

## ❓ 작성 이유

[4차 부하 테스트](https://github.com/dailyge/dailyge-server/pull/79#issuecomment-2294463801)에서 **`톰캣 설정 문제`** 로 트래픽을 제대로 처리하지 못했기 때문에 톰캣 설정에 대해 정리하기 위해 글을 작성하게 되었습니다.

![image](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2F8P7qx%2FbtsI7fGbIQw%2FUlLndzlF2q4CLhhiFOIe1k%2Fimg.png)

> 위 이미지는 서버 스펙(t3a.small)은 작은데 무작정 많은(600개) 쓰레드를 할당해, 부하 테스트에서 메모리 누수가 탐지된 서버의 상태입니다.

<br/><br/><br/><br/>

## 📝 내용

다양한 설정이 있지만 **`accept-count`**, **`max-connections`**, **`threads.max`**, **`threads.min-spare`** 정도만 살펴보겠습니다.

```yml
server:
  tomcat:
    accept-count: ${ACCEPT_COUNT}
    max-connections: ${MAX_CONNECTIONS}
    connection-timeout: 15000
    uri-encoding: UTF-8
    background-processor-delay: 10
    threads:
      max: ${MAX}
      min-spare: ${MIN_SPARE}
```

<br/><br/><br/><br/>

각 설정 값에 대한 내용은 다음과 같습니다. 

1. **`accept-count`**: 최대 대기열 크기를 정합니다. 이를 통해 서버가 모든 쓰레드를 사용 중일 때, 추가적인 연결 요청을 대기열에 쌓아둘 수 있습니다.
2. **`max-connections`**: 서버가 동시에 처리할 수 있는 최대 연결 수입니다. 이를 통해 네트워크 레벨에서 서버가 동시에 커넥션을 맺는 총연결 수를 조절할 수 있습니다.
3. **`threads.max`**: 서버가 처리할 수 있는 최대 쓰레드 수입니다.
4. **`threads.min-spare`**: 서버가 항상 유지해야 하는 최소 쓰레드 수입니다.

<br/><br/><br/><br/>

글이 길어져서 **`부하를 주며 테스트 했던 내용`** 은 [해당 링크](https://junwoo-dev.notion.site/Tomcat-30ff6b5c60f943d0818a04f5abf195b1?pvs=4)로 대체하겠습니다. 정리하면 다음과 같습니다. 

> max-connections 개수를 초과하면 accept-count에 들어가 대기하며, 이마저 초과하면 Connection Refuse가 발생한다.
